language: scala
jdk:
- oraclejdk8
env:
  global:
  - secure: SwxXgTaIfXPO1PEReGZApz8XqQUp04zbHo+HAuIvy6nHJtvhG4HM814NlLoQp3ZKvAXpIq3zRLKEkiTzoGIMDdl2iVp/sPllYPWRM0G8U76US4FPrYXdhDxP+bGCPZCYU8w8kvJ8Hbh1AAYC+g6r/W9RjXoshoCNQsOJvx/6fzo=
install: "./etc/travis-setup.sh"
script: sbt scripted
after_script: heroku keys:remove $USER@`hostname`
