language: scala
jdk:
- oraclejdk8
env:
  global:
  - secure: E9fa9IoS3ubb6plN9JzsTT7WQrP0GpKqA9VS4DJgcPQjKfHEiHnJAlURYNweBqL3fvKsaSzb2XVUVBTWHj6v5Y6ZBaPzmdwi66xQ+a9rMk86shihbo26Ov7d5JnUwaHY5jXFTcmL7V1YoJzp6aJCs1N0o7RT5Swuc2ubpNytJ8A=
install: "./etc/travis-setup.sh"
script: sbt scripted
after_script: heroku keys:remove $USER@`hostname`
