language: scala
env:
  global:
  - secure: SAzMU8NSxrOBZuQFgSG7KL5+qbejTxpvPJWpwlyhOmB/BosAhjxdy05zzEPA6X9O4Wjb5WcVPcls9V/bBRqd8xBQ4EqbnBcB37UfhUTOpdXlfNpB7Ga1xq5mec1wIvpXkTasT6mdN4tZJKHw2r8A3IEt01DTLYCsU5nnOlHyfJ0=
install: "./etc/travis-setup.sh"
script: sbt scripted
after_script: heroku keys:remove $USER@`hostname`
