language: scala
jdk:
- oraclejdk8
env:
  global:
  - secure: YM3tKqyUm8k360N2vV/sGROLEOK6VqTx/59orXU44FYmdmY8z3h4sEC3218kDh8845JCfbJyl/vxNhXkdeiz0vRCppUzHWdN4GF740r1P/nhrakh6dXSZqh27Baaat1EGI5NkLsoP0SzhF1HMZWplDbaQMXWdJVwafZBDpLElyQ=
install: "./etc/travis-setup.sh"
script: sbt scripted
after_script: heroku keys:remove $USER@`hostname`
